<?binding.jca InsertItemDB_db.jca?>
<wsdl:definitions name="InsertItemDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/ShoppingCartService/ShoppingCart/InsertItemDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/ShoppingCartService/ShoppingCart/InsertItemDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertItemDB">
    <plt:partnerLinkType name="InsertItemDB_plt">
        <plt:role name="InsertItemDB_role">
            <plt:portType name="tns:InsertItemDB_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertItemDB" schemaLocation="xsd/InsertItemDB_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="CartCollection_msg">
        <wsdl:part name="CartCollection" element="top:CartCollection"/>
    </wsdl:message>
    <wsdl:portType name="InsertItemDB_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:CartCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
