<?binding.jca DeleteFromCartDB_db.jca?>
<wsdl:definitions name="DeleteFromCartDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AddMerchandiseCartProcess/AddMerchandiseCart/DeleteFromCartDB" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/DeleteFromCartDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AddMerchandiseCartProcess/AddMerchandiseCart/DeleteFromCartDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="DeleteFromCartDB_plt">
        <plt:role name="DeleteFromCartDB_role">
            <plt:portType name="tns:DeleteFromCartDB_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DeleteFromCartDB" schemaLocation="xsd/DeleteFromCartDB.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="DeleteFromCartDBInput_msg">
        <wsdl:part name="DeleteFromCartDBInput_msg" element="db:DeleteFromCartDBInput"/>
    </wsdl:message>
    <wsdl:portType name="DeleteFromCartDB_ptt">
        <wsdl:operation name="DeleteFromCartDB">
            <wsdl:input message="tns:DeleteFromCartDBInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
